// build.rs -- Pre-rasterize Inter and JetBrains Mono fonts.
//
// Runs on the HOST (std available) via fontdue.
// Generates src/bitmaps_gen.rs containing static glyph tables
// that the kernel embeds directly — no runtime TrueType dependency.
//
// Rasterized sizes: 11, 12, 13, 14, 17 px (covers all Atelier UI sizes).
// Character range:  ASCII 32–126 (printable).

use std::env;
use std::fs;
use std::path::Path;
use std::fmt::Write;

const INTER_BYTES:  &[u8] = include_bytes!("assets/fonts/Inter-Regular.ttf");
const JBMONO_BYTES: &[u8] = include_bytes!("assets/fonts/JetBrainsMono-Regular.ttf");

const SIZES: &[f32]   = &[11.0, 12.0, 13.0, 14.0, 17.0];
const CHARS: &str      = " !\"#$%&'()*+,-./0123456789:;<=>?@\
                          ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`\
                          abcdefghijklmnopqrstuvwxyz{|}~";

fn rasterize(src: &str, bytes: &[u8], size: f32, out: &mut String) {
    let font = fontdue::Font::from_bytes(bytes, fontdue::FontSettings::default())
        .expect("failed to parse font");

    let size_id = (size * 10.0) as u32; // e.g. 110, 120, 130, 140, 170

    writeln!(out, "// {src} at {size}px").unwrap();
    writeln!(out, "pub const {}_S{}: &[GlyphEntry] = &[",
             src.to_uppercase(), size_id).unwrap();

    for ch in CHARS.chars() {
        let (metrics, bitmap) = font.rasterize(ch, size);
        let codepoint = ch as u32;

        write!(out, "    GlyphEntry {{ codepoint: {codepoint}, \
               width: {w}, height: {h}, xmin: {xmin}, ymin: {ymin}, \
               advance: {adv}, bitmap: &[",
               w   = metrics.width,
               h   = metrics.height,
               xmin = metrics.xmin,
               ymin = metrics.ymin,
               adv = (metrics.advance_width * 64.0) as i32,  // 1/64px fixed
        ).unwrap();

        for (i, &byte) in bitmap.iter().enumerate() {
            if i > 0 { write!(out, ",").unwrap(); }
            write!(out, "{byte}").unwrap();
        }
        writeln!(out, "] }},").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
}

fn main() {
    let out_dir  = env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("bitmaps_gen.rs");

    let mut src = String::with_capacity(1 << 20); // 1 MiB should be plenty

    writeln!(&mut src, "// AUTO-GENERATED by build.rs — do not edit by hand.").unwrap();
    writeln!(&mut src, "// Rasterized from Inter-Regular.ttf and JetBrainsMono-Regular.ttf").unwrap();
    writeln!(&mut src, "// via fontdue on the build host.").unwrap();
    writeln!(&mut src).unwrap();
    writeln!(&mut src, "#[repr(C)]").unwrap();
    writeln!(&mut src, "pub struct GlyphEntry {{").unwrap();
    writeln!(&mut src, "    pub codepoint: u32,").unwrap();
    writeln!(&mut src, "    pub width:     usize,").unwrap();
    writeln!(&mut src, "    pub height:    usize,").unwrap();
    writeln!(&mut src, "    pub xmin:      i32,").unwrap();
    writeln!(&mut src, "    pub ymin:      i32,").unwrap();
    writeln!(&mut src, "    pub advance:   i32,  // 1/64 pixel units").unwrap();
    writeln!(&mut src, "    pub bitmap:    &'static [u8],").unwrap();
    writeln!(&mut src, "}}").unwrap();
    writeln!(&mut src).unwrap();

    for &size in SIZES {
        rasterize("INTER",  INTER_BYTES,  size, &mut src);
        rasterize("JBMONO", JBMONO_BYTES, size, &mut src);
    }

    fs::write(&out_path, &src).unwrap();

    println!("cargo:rerun-if-changed=assets/fonts/Inter-Regular.ttf");
    println!("cargo:rerun-if-changed=assets/fonts/JetBrainsMono-Regular.ttf");
    println!("cargo:rerun-if-changed=build.rs");
    // Declare cfg flags so Rust doesn't warn about unknown cfg names.
    println!("cargo::rustc-check-cfg=cfg(c_toolchain_available)");
    println!("cargo::rustc-check-cfg=cfg(quickjs_available)");

    // ── Freestanding C sources ────────────────────────────────────────────────
    // Only compiled when targeting a bare-metal kernel (target_os = "none").
    // Set CC_x86_64_unknown_none or CC in the environment to override the
    // compiler (e.g. CC=clang or CC=x86_64-elf-gcc).
    // Compile C sources for x86_64 bare-metal only.
    // RISC-V kernel modules use a different ABI and don't link against these.
    let target_os   = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    if target_arch == "x86_64" && (target_os.is_empty() || target_os == "none") {
        compile_c_kernel_sources();
    }
}

// ── C kernel source compilation ───────────────────────────────────────────────

fn compile_c_kernel_sources() {
    use std::path::PathBuf;

    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let c_root   = manifest.join("c");
    if !c_root.exists() { return; }

    let (compiler, extra_flags) = detect_c_compiler();

    let mut build = cc::Build::new();
    build.compiler(&compiler);

    // Freestanding kernel flags — no hosted runtime, no red-zone, no SIMD.
    for flag in &[
        "-ffreestanding", "-nostdlib", "-fno-builtin", "-nostartfiles",
        "-m64", "-mno-red-zone", "-mno-mmx", "-mno-sse", "-mno-sse2",
        "-fno-stack-protector", "-O2", "-Wall",
    ] {
        build.flag(flag);
    }
    for flag in &extra_flags {
        build.flag(flag);
    }

    build.include(c_root.join("include"));

    // Compile subdirectories: root, runtime, streaming.
    // Examples and test files are excluded from the main build.
    let compile_dirs = [".", "runtime", "streaming"];
    let mut any = false;

    for sub in &compile_dirs {
        let dir = c_root.join(sub);
        if !dir.exists() { continue; }
        let entries = match std::fs::read_dir(&dir) {
            Ok(e) => e,
            Err(_) => continue,
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(false, |e| e == "c") {
                let name = path.file_name().unwrap().to_string_lossy().into_owned();
                // Skip explicit test files (compiled separately when needed).
                if name.starts_with("test_") { continue; }
                build.file(&path);
                println!("cargo:rerun-if-changed={}", path.display());
                any = true;
            }
        }
    }

    println!("cargo:rerun-if-changed={}", c_root.join("include").display());

    if any {
        build.compile("djinnos_c");
        println!("cargo:rustc-link-lib=static=djinnos_c");
        println!("cargo:rustc-cfg=c_toolchain_available");
    }

    // ── QuickJS (Faerie JS engine) ────────────────────────────────────────────
    let qjs_dir = c_root.join("quickjs");
    if qjs_dir.exists() {
        compile_quickjs_sources(&qjs_dir, &compiler, &extra_flags);
    }
}

fn compile_quickjs_sources(
    qjs_dir:      &std::path::Path,
    compiler:     &str,
    extra_flags:  &[String],
) {
    // Only these files are needed for the evaluation core.
    // qjs.c / qjsc.c have their own main(); libbf.c (BigFloat) is optional.
    // libbf.c is always included by quickjs.c (unconditional #include "libbf.h").
    let qjs_files = ["libbf.c", "quickjs.c", "cutils.c",
                     "libregexp.c", "libunicode.c", "djinnos_js.c"];

    let mut build = cc::Build::new();
    build.compiler(compiler);

    // QuickJS needs the port header first (overrides malloc/free/FILE).
    // We use clang's own resource headers for freestanding C primitives
    // (stdint.h, stdarg.h, stdatomic.h, etc.) rather than host stdlib.
    // Host stdlib paths are excluded via -nostdlibinc (not -nostdinc so that
    // clang's own resource directory is still searched).
    let port = qjs_dir.join("djinnos_port.h");
    // QuickJS uses double arithmetic which requires SSE on x86-64.
    // We allow SSE here — QuickJS is called cooperatively (not from IRQ context)
    // so clobbering XMM caller-saved registers is safe.
    // We still keep -mno-red-zone because we're in kernel stack space.
    for flag in &[
        "-ffreestanding", "-nostdlib", "-fno-builtin",
        "-nostdlibinc",
        "-m64", "-mno-red-zone",
        "-fno-stack-protector", "-O1", "-w",
    ] {
        build.flag(flag);
    }
    build.flag(&format!("-include{}", port.display()));
    for flag in extra_flags {
        build.flag(flag);
    }

    // QuickJS headers (quickjs.h, cutils.h, etc.) + our port stubs.
    build.include(qjs_dir);

    let mut any = false;
    for name in &qjs_files {
        let path = qjs_dir.join(name);
        if path.exists() {
            build.file(&path);
            println!("cargo:rerun-if-changed={}", path.display());
            any = true;
        }
    }

    if any {
        build.compile("djinnos_qjs");
        println!("cargo:rustc-link-lib=static=djinnos_qjs");
        println!("cargo:rustc-cfg=quickjs_available");
    }
}

fn detect_c_compiler() -> (String, Vec<String>) {
    // Priority: env override → clang (cross-target) → ELF GCC → Linux GCC.
    if let Ok(cc) = env::var("CC_x86_64_unknown_none").or_else(|_| env::var("CC")) {
        return (cc, vec![]);
    }
    // Clang can target bare-metal via --target.
    if tool_exists("clang") {
        return ("clang".into(), vec![
            "--target=x86_64-unknown-none-elf".into(),
        ]);
    }
    if tool_exists("x86_64-elf-gcc")       { return ("x86_64-elf-gcc".into(),       vec![]); }
    if tool_exists("x86_64-linux-gnu-gcc") { return ("x86_64-linux-gnu-gcc".into(), vec![]); }
    // Last resort — may not produce bare-metal ELF on all platforms.
    println!("cargo:warning=No bare-metal C cross-compiler found; \
              set CC_x86_64_unknown_none or CC to fix. Trying 'gcc'.");
    ("gcc".into(), vec!["-m64".into()])
}

fn tool_exists(name: &str) -> bool {
    std::process::Command::new(name).arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status().is_ok()
}
