// build.rs -- Pre-rasterize Inter and JetBrains Mono fonts.
//
// Runs on the HOST (std available) via fontdue.
// Generates src/bitmaps_gen.rs containing static glyph tables
// that the kernel embeds directly — no runtime TrueType dependency.
//
// Rasterized sizes: 11, 12, 13, 14, 17 px (covers all Atelier UI sizes).
// Character range:  ASCII 32–126 (printable).

use std::env;
use std::fs;
use std::path::Path;
use std::fmt::Write;

const INTER_BYTES:  &[u8] = include_bytes!("assets/fonts/Inter-Regular.ttf");
const JBMONO_BYTES: &[u8] = include_bytes!("assets/fonts/JetBrainsMono-Regular.ttf");

const SIZES: &[f32]   = &[11.0, 12.0, 13.0, 14.0, 17.0];
const CHARS: &str      = " !\"#$%&'()*+,-./0123456789:;<=>?@\
                          ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`\
                          abcdefghijklmnopqrstuvwxyz{|}~";

fn rasterize(src: &str, bytes: &[u8], size: f32, out: &mut String) {
    let font = fontdue::Font::from_bytes(bytes, fontdue::FontSettings::default())
        .expect("failed to parse font");

    let size_id = (size * 10.0) as u32; // e.g. 110, 120, 130, 140, 170

    writeln!(out, "// {src} at {size}px").unwrap();
    writeln!(out, "pub const {}_S{}: &[GlyphEntry] = &[",
             src.to_uppercase(), size_id).unwrap();

    for ch in CHARS.chars() {
        let (metrics, bitmap) = font.rasterize(ch, size);
        let codepoint = ch as u32;

        write!(out, "    GlyphEntry {{ codepoint: {codepoint}, \
               width: {w}, height: {h}, xmin: {xmin}, ymin: {ymin}, \
               advance: {adv}, bitmap: &[",
               w   = metrics.width,
               h   = metrics.height,
               xmin = metrics.xmin,
               ymin = metrics.ymin,
               adv = (metrics.advance_width * 64.0) as i32,  // 1/64px fixed
        ).unwrap();

        for (i, &byte) in bitmap.iter().enumerate() {
            if i > 0 { write!(out, ",").unwrap(); }
            write!(out, "{byte}").unwrap();
        }
        writeln!(out, "] }},").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
}

fn main() {
    let out_dir  = env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("bitmaps_gen.rs");

    let mut src = String::with_capacity(1 << 20); // 1 MiB should be plenty

    writeln!(&mut src, "// AUTO-GENERATED by build.rs — do not edit by hand.").unwrap();
    writeln!(&mut src, "// Rasterized from Inter-Regular.ttf and JetBrainsMono-Regular.ttf").unwrap();
    writeln!(&mut src, "// via fontdue on the build host.").unwrap();
    writeln!(&mut src).unwrap();
    writeln!(&mut src, "#[repr(C)]").unwrap();
    writeln!(&mut src, "pub struct GlyphEntry {{").unwrap();
    writeln!(&mut src, "    pub codepoint: u32,").unwrap();
    writeln!(&mut src, "    pub width:     usize,").unwrap();
    writeln!(&mut src, "    pub height:    usize,").unwrap();
    writeln!(&mut src, "    pub xmin:      i32,").unwrap();
    writeln!(&mut src, "    pub ymin:      i32,").unwrap();
    writeln!(&mut src, "    pub advance:   i32,  // 1/64 pixel units").unwrap();
    writeln!(&mut src, "    pub bitmap:    &'static [u8],").unwrap();
    writeln!(&mut src, "}}").unwrap();
    writeln!(&mut src).unwrap();

    for &size in SIZES {
        rasterize("INTER",  INTER_BYTES,  size, &mut src);
        rasterize("JBMONO", JBMONO_BYTES, size, &mut src);
    }

    fs::write(&out_path, &src).unwrap();

    println!("cargo:rerun-if-changed=assets/fonts/Inter-Regular.ttf");
    println!("cargo:rerun-if-changed=assets/fonts/JetBrainsMono-Regular.ttf");
    println!("cargo:rerun-if-changed=build.rs");
}
