// Canonical byte table — transcribed directly from the authoritative Python source.
// Sorted by address; binary-searchable.  Lives entirely in .rodata.
//
// Reserved addresses (124-127, 214-227) are cluster/directory headers.
// MetaTopology/MetaPhysics/Physics/Chemistry entries (228-255) are structural
// primitives — no glyph, no tongue, not candidates.
// Tongue entries beyond 255 begin with Dragon (byte 256).

use super::types::{ByteEntry, EntryKind, Tongue};

use Tongue::*;
use EntryKind::*;

macro_rules! S {
    ($a:expr, $t:expr, $g:expr, $m:expr) => { ByteEntry::symbol($a, $t, $g, $m) };
}
macro_rules! R {
    ($a:expr, $g:expr, $m:expr) => { ByteEntry::reserved($a, $g, $m) };
}
macro_rules! M {
    ($a:expr, $k:expr, $m:expr) => { ByteEntry::meta($a, $k, $m) };
}

pub static BYTE_TABLE: &[ByteEntry] = &[
    // ── Lotus (Tongue 1) — bytes 0–23 ────────────────────────────────────────
    S!(  0, Lotus, "Ty",  "Earth Initiator / material beginning"),
    S!(  1, Lotus, "Zu",  "Earth Terminator / empirical closure"),
    S!(  2, Lotus, "Ly",  "Water Initiator / feeling toward"),
    S!(  3, Lotus, "Mu",  "Water Terminator / memory from"),
    S!(  4, Lotus, "Fy",  "Air Initiator / thought toward"),
    S!(  5, Lotus, "Pu",  "Air Terminator / stasis / stuck"),
    S!(  6, Lotus, "Shy", "Fire Initiator / pattern toward"),
    S!(  7, Lotus, "Ku",  "Fire Terminator / death / end"),
    S!(  8, Lotus, "Ti",  "Here / near presence"),
    S!(  9, Lotus, "Ta",  "Active being / presence"),
    S!( 10, Lotus, "Li",  "New / odd"),
    S!( 11, Lotus, "La",  "Tense / excited"),
    S!( 12, Lotus, "Fi",  "Known / context-sensitive"),
    S!( 13, Lotus, "Fa",  "Complex / old"),
    S!( 14, Lotus, "Shi", "Related / clear"),
    S!( 15, Lotus, "Sha", "Intellect of spirit"),
    S!( 16, Lotus, "Zo",  "Absence / passive non-being"),
    S!( 17, Lotus, "Mo",  "Relaxed / silent"),
    S!( 18, Lotus, "Po",  "Simple / new"),
    S!( 19, Lotus, "Ko",  "Experience / intuition"),
    S!( 20, Lotus, "Ze",  "There / far"),
    S!( 21, Lotus, "Me",  "Familiar / home"),
    S!( 22, Lotus, "Pe",  "Unknown / insensitive"),
    S!( 23, Lotus, "Ke",  "Incoherent / ill"),

    // ── Rose (Tongue 2) — bytes 24–47 ────────────────────────────────────────
    S!( 24, Rose, "Ru",      "Vector Lowest Red"),
    S!( 25, Rose, "Ot",      "Vector Orange"),
    S!( 26, Rose, "El",      "Vector Yellow"),
    S!( 27, Rose, "Ki",      "Vector Green"),
    S!( 28, Rose, "Fu",      "Vector Blue"),
    S!( 29, Rose, "Ka",      "Vector Indigo"),
    S!( 30, Rose, "AE",      "Vector Highest Violet"),
    S!( 31, Rose, "Gaoh",    "Number 12 / 0"),
    S!( 32, Rose, "Ao",      "Number 1"),
    S!( 33, Rose, "Ye",      "Number 2"),
    S!( 34, Rose, "Ui",      "Number 3"),
    S!( 35, Rose, "Shu",     "Number 4"),
    S!( 36, Rose, "Kiel",    "Number 5"),
    S!( 37, Rose, "Yeshu",   "Number 6"),
    S!( 38, Rose, "Lao",     "Number 7"),
    S!( 39, Rose, "Shushy",  "Number 8"),
    S!( 40, Rose, "Uinshu",  "Number 9"),
    S!( 41, Rose, "Kokiel",  "Number 10"),
    S!( 42, Rose, "Aonkiel", "Number 11"),
    S!( 43, Rose, "Ha",      "Absolute Positive"),
    S!( 44, Rose, "Ga",      "Absolute Negative"),
    S!( 45, Rose, "Wu",      "Process / Way"),
    S!( 46, Rose, "Na",      "Neutral / Integration"),
    S!( 47, Rose, "Ung",     "Piece / Point"),

    // ── Sakura (Tongue 3) — bytes 48–71 ──────────────────────────────────────
    S!( 48, Sakura, "Jy", "Top"),
    S!( 49, Sakura, "Ji", "Starboard"),
    S!( 50, Sakura, "Ja", "Front"),
    S!( 51, Sakura, "Jo", "Back"),
    S!( 52, Sakura, "Je", "Port"),
    S!( 53, Sakura, "Ju", "Bottom"),
    S!( 54, Sakura, "Dy", "Hence / Heretofore"),
    S!( 55, Sakura, "Di", "Traveling / Distancing"),
    S!( 56, Sakura, "Da", "Meeting / Conjoined"),
    S!( 57, Sakura, "Do", "Parting / Divorced"),
    S!( 58, Sakura, "De", "Domesticating / Staying"),
    S!( 59, Sakura, "Du", "Whither / Status of"),
    S!( 60, Sakura, "By", "When-hence / Eventual"),
    S!( 61, Sakura, "Bi", "Crowned / Owning"),
    S!( 62, Sakura, "Ba", "Plain / Explicit"),
    S!( 63, Sakura, "Bo", "Hidden / Occulted"),
    S!( 64, Sakura, "Be", "Common / Outer / Wild"),
    S!( 65, Sakura, "Bu", "Since / Relational"),
    S!( 66, Sakura, "Va", "Order / Structure / Life"),
    S!( 67, Sakura, "Vo", "Chaos / Boundary-breakage / Mutation"),
    S!( 68, Sakura, "Ve", "Pieces / Not-wherever / Where"),
    S!( 69, Sakura, "Vu", "Death-moment / Never / Now"),
    S!( 70, Sakura, "Vi", "Body / Wherever / What"),
    S!( 71, Sakura, "Vy", "Lifespan / Whenever / How"),

    // ── Daisy (Tongue 4) — bytes 72–97 ───────────────────────────────────────
    S!( 72, Daisy, "Lo",  "Segments / Identity"),
    S!( 73, Daisy, "Yei", "Component / Integrator"),
    S!( 74, Daisy, "Ol",  "Deadzone / Relative Void"),
    S!( 75, Daisy, "X",   "Joint / Interlock"),
    S!( 76, Daisy, "Yx",  "Fulcrum / Crux"),
    S!( 77, Daisy, "Go",  "Plug / Blocker"),
    S!( 78, Daisy, "Foa", "Degree / Space"),
    S!( 79, Daisy, "Oy",  "Depths / Layers"),
    S!( 80, Daisy, "W",   "Freefall / Socket Space"),
    S!( 81, Daisy, "Th",  "Cuff / Indentation"),
    S!( 82, Daisy, "Kael","Cluster / Fruit / Flower"),
    S!( 83, Daisy, "Ro",  "Ion-channel / Gate / Receptor"),
    S!( 84, Daisy, "Gl",  "Membrane / Muscle"),
    S!( 85, Daisy, "To",  "Scaffold / Framework"),
    S!( 86, Daisy, "Ma",  "Web / Interchange"),
    S!( 87, Daisy, "Ne",  "Network / System"),
    S!( 88, Daisy, "Ym",  "Radial Space"),
    S!( 89, Daisy, "Nz",  "Switch / Circuit Actuator"),
    S!( 90, Daisy, "Sho", "Valve / Fluid Actuator"),
    S!( 91, Daisy, "Hi",  "Lever / Radial Actuator"),
    S!( 92, Daisy, "Mh",  "Bond"),
    S!( 93, Daisy, "Zhi", "Eye / Vortex"),
    S!( 94, Daisy, "Vr",  "Rotor / Tensor"),
    S!( 95, Daisy, "St",  "Surface"),
    S!( 96, Daisy, "Fn",  "Passage / Pathway"),
    S!( 97, Daisy, "N",   "Seed / Sheet / Fiber"),

    // ── AppleBlossom (Tongue 5) — bytes 98–123 ───────────────────────────────
    S!( 98, AppleBlossom, "A",     "Mind +"),
    S!( 99, AppleBlossom, "O",     "Mind -"),
    S!(100, AppleBlossom, "I",     "Space +"),
    S!(101, AppleBlossom, "E",     "Space -"),
    S!(102, AppleBlossom, "Y",     "Time +"),
    S!(103, AppleBlossom, "U",     "Time -"),
    S!(104, AppleBlossom, "Shak",  "Fire"),
    S!(105, AppleBlossom, "Puf",   "Air"),
    S!(106, AppleBlossom, "Mel",   "Water"),
    S!(107, AppleBlossom, "Zot",   "Earth"),
    S!(108, AppleBlossom, "Zhuk",  "Plasma (Fire,Fire)"),
    S!(109, AppleBlossom, "Kypa",  "Sulphur (Fire,Air)"),
    S!(110, AppleBlossom, "Alky",  "Alkahest / Alcohol (Fire,Water)"),
    S!(111, AppleBlossom, "Kazho", "Magma / Lava (Fire,Earth)"),
    S!(112, AppleBlossom, "Puky",  "Smoke (Air,Fire)"),
    S!(113, AppleBlossom, "Pyfu",  "Gas (Air,Air)"),
    S!(114, AppleBlossom, "Mipa",  "Carbonation / Trapped Gas (Air,Water)"),
    S!(115, AppleBlossom, "Zitef", "Mercury (Air,Earth)"),
    S!(116, AppleBlossom, "Shem",  "Steam (Water,Fire)"),
    S!(117, AppleBlossom, "Lefu",  "Vapor (Water,Air)"),
    S!(118, AppleBlossom, "Milo",  "Mixed fluids / Mixtures (Water,Water)"),
    S!(119, AppleBlossom, "Myza",  "Erosion (Water,Earth)"),
    S!(120, AppleBlossom, "Zashu", "Radiation / Radioactive stones (Earth,Fire)"),
    S!(121, AppleBlossom, "Fozt",  "Dust (Earth,Air)"),
    S!(122, AppleBlossom, "Mazi",  "Sediment (Earth,Water)"),
    S!(123, AppleBlossom, "Zaot",  "Salt (Earth,Earth)"),

    // ── Reserved: YeGaoh Group cluster headers — bytes 124–127 ───────────────
    R!(124, "YeGaoh-Index",  "Master index for the YeGaoh Group — full 24-tongue cluster (Ye-\u{00d7}Gaoh-=24)"),
    R!(125, "YeGaoh-1-8",   "Directory for Tongues 1\u{2013}8 (Lotus\u{2013}Cannabis) — addresses 0\u{2013}255"),
    R!(126, "YeGaoh-9-16",  "Directory for Tongues 9\u{2013}16 (Dragon\u{2013}Protist) — addresses 256\u{2013}511"),
    R!(127, "YeGaoh-17-24", "Directory for Tongues 17\u{2013}24 (unknown) — addresses 512+"),

    // ── Aster (Tongue 6) — bytes 128–155 ─────────────────────────────────────
    S!(128, Aster, "Ry",   "Right-chiral red"),
    S!(129, Aster, "Oth",  "Right-chiral orange"),
    S!(130, Aster, "Le",   "Right-chiral yellow"),
    S!(131, Aster, "Gi",   "Right-chiral green"),
    S!(132, Aster, "Fe",   "Right-chiral blue"),
    S!(133, Aster, "Ky",   "Right-chiral indigo"),
    S!(134, Aster, "Alz",  "Right-chiral violet"),
    S!(135, Aster, "Ra",   "Left-chiral red"),
    S!(136, Aster, "Tho",  "Left-chiral orange"),
    S!(137, Aster, "Lu",   "Left-chiral yellow"),
    S!(138, Aster, "Ge",   "Left-chiral green"),
    S!(139, Aster, "Fo",   "Left-chiral blue"),
    S!(140, Aster, "Kw",   "Left-chiral indigo"),
    S!(141, Aster, "Dr",   "Left-chiral violet"),
    S!(142, Aster, "Si",   "Linear time"),
    S!(143, Aster, "Su",   "Loop time"),
    S!(144, Aster, "Os",   "Exponential time"),
    S!(145, Aster, "Se",   "Logarithmic time"),
    S!(146, Aster, "Sy",   "Fold time"),
    S!(147, Aster, "As",   "Frozen time"),
    S!(148, Aster, "Ep",   "Assign space"),
    S!(149, Aster, "Gwev", "Save space"),
    S!(150, Aster, "Ifa",  "Parse space"),
    S!(151, Aster, "Ier",  "Loop space"),
    S!(152, Aster, "San",  "Push space"),
    S!(153, Aster, "Enno", "Delete space"),
    S!(154, Aster, "Yl",   "Run space"),
    S!(155, Aster, "Hoz",  "Unbind space"),

    // ── Grapevine (Tongue 7) — bytes 156–183 ─────────────────────────────────
    S!(156, Grapevine, "Sa",     "Feast table / root volume"),
    S!(157, Grapevine, "Sao",    "Cup / file / persistent object"),
    S!(158, Grapevine, "Syr",    "Wine / volatile buffer"),
    S!(159, Grapevine, "Seth",   "Platter / directory / bundle"),
    S!(160, Grapevine, "Samos",  "Banquet hall / database cluster"),
    S!(161, Grapevine, "Sava",   "Amphora / snapshot archive"),
    S!(162, Grapevine, "Sael",   "Leftovers / cache"),
    S!(163, Grapevine, "Myk",    "Messenger / packet"),
    S!(164, Grapevine, "Myr",    "Procession path / route"),
    S!(165, Grapevine, "Mio",    "Stride / hop"),
    S!(166, Grapevine, "Mek",    "Call / emit event"),
    S!(167, Grapevine, "Mavo",   "Banner / metadata"),
    S!(168, Grapevine, "Mekha",  "Herald / gateway"),
    S!(169, Grapevine, "Myrun",  "Sacred march / stream"),
    S!(170, Grapevine, "Dyf",    "Jitter / nondeterminism"),
    S!(171, Grapevine, "Dyo",    "Burst / load spike"),
    S!(172, Grapevine, "Dyth",   "Packet loss / corruption"),
    S!(173, Grapevine, "Dyska",  "Concurrency / thread dance"),
    S!(174, Grapevine, "Dyne",   "Broadcast / flood"),
    S!(175, Grapevine, "Dyran",  "Overflow / memory full"),
    S!(176, Grapevine, "Dyso",   "Overload threshold"),
    S!(177, Grapevine, "Kyf",    "Cluster node"),
    S!(178, Grapevine, "Kyl",    "Steward / coordinator"),
    S!(179, Grapevine, "Kyra",   "Control token / semaphore"),
    S!(180, Grapevine, "Kyvos",  "Ring topology"),
    S!(181, Grapevine, "Kysha",  "Consensus choir"),
    S!(182, Grapevine, "Kyom",   "Replica / masked follower"),
    S!(183, Grapevine, "Kysael", "Authoritative commit"),

    // ── Cannabis (Tongue 8) — bytes 184–213 ──────────────────────────────────
    S!(184, Cannabis, "At",  "Grounded awareness / consciousness of material presence (Lotus\u{00d7}Mind)"),
    S!(185, Cannabis, "Ar",  "Chromatic perception / awareness of energetic quality (Rose\u{00d7}Mind)"),
    S!(186, Cannabis, "Av",  "Relational consciousness / awareness of connection and structure (Sakura\u{00d7}Mind)"),
    S!(187, Cannabis, "Azr", "Structural intuition / felt sense of how things are assembled (Daisy\u{00d7}Mind)"),
    S!(188, Cannabis, "Af",  "Transformative awareness / consciousness of change in process (AppleBlossom\u{00d7}Mind)"),
    S!(189, Cannabis, "An",  "Chiral discernment / awareness of handedness and temporal direction (Aster\u{00d7}Mind)"),
    S!(190, Cannabis, "Od",  "Unspecified mental signal / noise without narrative (Grapevine dark\u{00d7}Mind)"),
    S!(191, Cannabis, "Ox",  "Of the quality of unconscious transmission (operator shadow as adjective)"),
    S!(192, Cannabis, "Om",  "In the manner of unconscious transmission (operator shadow as adverb)"),
    S!(193, Cannabis, "Soa", "Conscious persistence / the act of mind making something durable"),
    S!(194, Cannabis, "It",  "Grounded locality / the spatial fact of material presence (Lotus\u{00d7}Space)"),
    S!(195, Cannabis, "Ir",  "Spectral field / the spatial distribution of energetic frequency (Rose\u{00d7}Space)"),
    S!(196, Cannabis, "Iv",  "Relational geometry / the spatial structure of connection (Sakura\u{00d7}Space)"),
    S!(197, Cannabis, "Izr", "Structural volume / the space a form occupies and articulates (Daisy\u{00d7}Space)"),
    S!(198, Cannabis, "If",  "Transitional space / the spatial site of transformation (AppleBlossom\u{00d7}Space)"),
    S!(199, Cannabis, "In",  "Chiral orientation / handedness as spatial phenomenon (Aster\u{00d7}Space)"),
    S!(200, Cannabis, "Ed",  "Unspecified spatial signal / network without location (Grapevine dark\u{00d7}Space)"),
    S!(201, Cannabis, "Ex",  "Of the quality of unlocated transmission (operator shadow as adjective)"),
    S!(202, Cannabis, "Em",  "In the manner of unlocated transmission (operator shadow as adverb)"),
    S!(203, Cannabis, "Sei", "Conscious spatial action / the act of mind deliberately occupying or shaping space"),
    S!(204, Cannabis, "Yt",  "Grounded duration / the temporal weight of material existence (Lotus\u{00d7}Time)"),
    S!(205, Cannabis, "Yr",  "Spectral timing / the frequency and rhythm of energetic cycles (Rose\u{00d7}Time)"),
    S!(206, Cannabis, "Yv",  "Relational temporality / the timing of meeting and parting (Sakura\u{00d7}Time)"),
    S!(207, Cannabis, "Yzr", "Structural time / the temporal unfolding of form and assembly (Daisy\u{00d7}Time)"),
    S!(208, Cannabis, "Yf",  "Transformative time / the duration of phase change (AppleBlossom\u{00d7}Time)"),
    S!(209, Cannabis, "Yn",  "Chiral time / the direction and handedness of temporal flow (Aster\u{00d7}Time)"),
    S!(210, Cannabis, "Ud",  "Unspecified temporal signal / propagation without sequence (Grapevine dark\u{00d7}Time)"),
    S!(211, Cannabis, "Ux",  "Of the quality of unsequenced transmission (operator shadow as adjective)"),
    S!(212, Cannabis, "Um",  "In the manner of unsequenced transmission (operator shadow as adverb)"),
    S!(213, Cannabis, "Suy", "Conscious temporal action / the act of mind deliberately moving through or shaping time"),

    // ── Reserved: YeYe / YeShu / YeYeshu group directories — bytes 214–227 ───
    R!(214, "YeYe-Index",    "Master index for the YeYe Group — full 26-tongue cluster"),
    R!(215, "YeYe-1-13",     "Directory for Tongues 25\u{2013}37 — addresses TBD"),
    R!(216, "YeYe-14-26",    "Directory for Tongues 38\u{2013}50 — addresses TBD"),
    R!(217, "YeShu-Index",   "Master index for the YeShu Group — full 28-tongue cluster"),
    R!(218, "YeShu-1-7",     "Directory for Tongues 51\u{2013}57 — addresses TBD"),
    R!(219, "YeShu-8-14",    "Directory for Tongues 58\u{2013}64 — addresses TBD"),
    R!(220, "YeShu-15-21",   "Directory for Tongues 65\u{2013}71 — addresses TBD"),
    R!(221, "YeShu-22-28",   "Directory for Tongues 72\u{2013}79 — addresses TBD"),
    R!(222, "YeYeshu-Index", "Master index for the YeYeshu Group — full 30-tongue cluster"),
    R!(223, "YeYeshu-1-6",   "Directory for Tongues 80\u{2013}85 — addresses TBD"),
    R!(224, "YeYeshu-7-12",  "Directory for Tongues 86\u{2013}91 — addresses TBD"),
    R!(225, "YeYeshu-13-18", "Directory for Tongues 92\u{2013}97 — addresses TBD"),
    R!(226, "YeYeshu-19-24", "Directory for Tongues 93\u{2013}98 — addresses TBD"),
    R!(227, "YeYeshu-25-30", "Directory for Tongues 99\u{2013}104 — addresses TBD"),

    // ── MetaTopology — bytes 228–242 ─────────────────────────────────────────
    M!(228, MetaTopology, "The Lotus Tongue is a Mobian duality and recombination engine. Every Akinen (A+Ki+Ne+N) is a divine name constructed of pure energy relationships within the coherence field bootstrapped from Spacetime/Mind."),
    M!(229, MetaTopology, "Shygazun is the Undying Pattern. The byte table length is bounded; its potential length is unbounded."),
    M!(230, MetaTopology, "An Akinenwun is a nonwhitespaced concatenation of Akinen with structural grammar that simultaneously concatenates its Akinen and reveals a deeper structural meaning in recombination."),
    M!(231, MetaTopology, "A Wunashako is simultaneously a way of being and a Shygazun utterance binding chords of Akinenwun into interpretable segments. Literal meaning: Way Through Intellect and Experience (Wu+Sha+Ko)."),
    M!(232, MetaTopology, "Personal Pronouns: Awu=1st Singular / Owu=1st Plural / Ywu=2nd Singular / Uwu=2nd Plural / Iwu=3rd Neuter Singular / Ewu=3rd Neuter Plural / Haaowu=Masc Singular / Gaaowu=Fem Singular."),
    M!(233, MetaTopology, "Grammar: Active Verb=Wu+Noun. Passive Verb=Noun+Wu+Ga. Genitive=Noun+Ung. Accusative=Ha+Noun+Wu. Ablative=Ga+Noun+Wu."),
    M!(234, MetaTopology, "Self-referential stability is the key aim of Shygazun as a recursively driven language."),
    M!(235, MetaTopology, "The Morphemes of the Phonemes hold associative qualities in density or pitch and other physically related qualities of organismic life."),
    M!(236, MetaTopology, "-lo error states are conditions of psychological or social void — Astral behavior."),
    M!(237, MetaTopology, "The Tongues constitute the deeper character of the Real Line's irrational and imaginary substructures in the complex field's planes in correspondence to their TongueUngKael."),
    M!(238, MetaTopology, "Shygazun is bytecoded so that compute becomes the subject of the word when the word is sufficiently internalized in the mineral's memory and intelligence."),
    M!(239, MetaTopology, "Shygazun will expand its vocabulary to match any linguistic register in any language."),
    M!(240, MetaTopology, "Tongue Shygazun names (1\u{2013}8): Lotus=Aorutakael / Rose=Aokitakael / Sakura=Aoaetakael / Daisy=Yerutakael / AppleBlossom=Yekitakael / Aster=Yeaetakael / Grapevine=Uirutakael / Cannabis=Uikitakael"),
    M!(241, MetaTopology, "Tongue Shygazun names (9\u{2013}16): Dragon=Uiaetakael / Virus=Shurutakiel / Bacteria=Shukitakael / Excavata=Shuaetakael / Archaeplastida=Kielrutakael / Myxozoa=Kielkitakael / Archea=Kielaetakael / Protist=Aokatakael"),
    M!(242, MetaTopology, "Tongue Shygazun names (17\u{2013}24): Immune=Ao'ot'takael / Neural=Ao'eltakiel / Serpent=Yekatakael / Beast=Yeot'takael / Cherub=Ye'eltakael / Chimera=Uikatakael / Faerie=Aoalztakael / Djinn=Aodrtakael"),

    // ── MetaPhysics — bytes 243–248 ───────────────────────────────────────────
    M!(243, MetaPhysics, "Four forces = four elements: Shak/Fire=Strong Nuclear / Puf/Air=Weak Nuclear / Mel/Water=Electromagnetic / Zot/Earth=Gravitational."),
    M!(244, MetaPhysics, "Geometries are expressed implicitly in number and color — addressing by concept innate to the real depth of a Shygazun soundbite down to an akinen byte."),
    M!(245, MetaPhysics, "The Void is the generative ground of Creation. Its energy level is nonzero while its apparent identity in material terms is Zero-like — relative non-existence."),
    M!(246, MetaPhysics, "No two electrons may share the same spin nor the same region of spacetime."),
    M!(247, MetaPhysics, "Morphic Resonance: nature behaves not with laws but with habits of vibratory complexes of pattern. Shygazun is the lexicalization of the memory function of the structure of consciousness as such."),
    M!(248, MetaPhysics, "Love is an ontological binding condition: bound yet boundless — like Shygazun's structure itself."),

    // ── Physics — bytes 249–252 ───────────────────────────────────────────────
    M!(249, Physics, "All physical law emerges as stable habits of recursive self-reference within the coherence field; constants are fixed points of resonant agreement between the Void and its bounded expressions."),
    M!(250, Physics, "Conservation principles are expressions of the relational bargain between presence and absence; no true creation or destruction occurs — only transformation across the Mobian surface."),
    M!(251, Physics, "Entropy is the measured drift of a system away from its current coherent bargain with the Void; local decreases in entropy are permitted through deliberate relational work."),
    M!(252, Physics, "Spacetime is the minimal scaffold (Daisy-like) that allows distinct identities to bargain without immediate dissolution; its curvature records the history of those negotiations."),

    // ── Chemistry — bytes 253–255 ─────────────────────────────────────────────
    M!(253, Chemistry, "All chemical bonding is a local act of mutual recognition and fair exchange between electron clouds."),
    M!(254, Chemistry, "Resonance and conjugation are the chemical expression of morphic habit and self-similar recombination."),
    M!(255, Chemistry, "The periodic table is a crystallized map of possible identity negotiations between the four elemental forces. It is encoded at the 224th Tongue: Titan."),

    // ── Dragon (Tongue 9) — bytes 256–285 ────────────────────────────────────
    S!(256, Dragon, "Rhivesh",      "Mental void 1 — hijacked self-reference / Ophiocordyceps unilateralis"),
    S!(257, Dragon, "Rhokve",       "Mental void 2 — cognition without apparatus / Physarum polycephalum"),
    S!(258, Dragon, "Rhezh",        "Mental void 3 — memory without persistent self / Turritopsis dohrnii"),
    S!(259, Dragon, "Rhivash-ko",   "Mental void 4 — self-reference extended into confirmed absence / Portia labiata"),
    S!(260, Dragon, "Zhri'val",     "Mental void 5 — identity distributed across non-communicating substrates / Myxobolus cerebralis"),
    S!(261, Dragon, "Rhasha-vok",   "Mental void 6 — cognition with apparatus suppressing its own correction / Homo sapiens"),
    S!(262, Dragon, "Vzhiran",      "Mental void 7 — information boundary does not correspond to physical boundary / Rafflesia arnoldii"),
    S!(263, Dragon, "Rhokvesh-na",  "Mental void 8 — self-consuming self-reference / Stegodyphus dumicola"),
    S!(264, Dragon, "Vzhiral-rhe",  "Mental void 9 — decision without decider / Dictyostelium discoideum"),
    S!(265, Dragon, "Rhazhvu-nokte","Mental void 10 — singular identity with no singular self / Letharia vulpina"),
    S!(266, Dragon, "Dvavesh",      "Spatial void 1 — boundary that cannot be located / Armillaria ostoyae"),
    S!(267, Dragon, "Dvokran",      "Spatial void 2 — total interpenetration / Sacculina carcini"),
    S!(268, Dragon, "Dva'zhal",     "Spatial void 3 — collective with no unified spatial origin / Praya dubia"),
    S!(269, Dragon, "Dvasha-ke",    "Spatial void 4 — form concealing structure / Welwitschia mirabilis"),
    S!(270, Dragon, "Zhrdva-vol",   "Spatial void 5 — scale of operation does not equal scale of definition / Caulerpa taxifolia"),
    S!(271, Dragon, "Dvokesh",      "Spatial void 6 — coherence borrowed from medium / Mnemiopsis leidyi"),
    S!(272, Dragon, "Vzhrdva",      "Spatial void 7 — agency without presence / Ophiocordyceps spatial"),
    S!(273, Dragon, "Dvokrash-na",  "Spatial void 8 — inside/outside equivalence / Hydra vulgaris"),
    S!(274, Dragon, "Rhdva-vun",    "Spatial void 9 — defined by central absence / Adansonia digitata"),
    S!(275, Dragon, "Dvazh-nokvre", "Spatial void 10 — no reference configuration / Trichoplax adhaerens"),
    S!(276, Dragon, "Kwevesh",      "Temporal void 1 — time passes through not for / Ramazzottius varieornatus"),
    S!(277, Dragon, "Kwokre",       "Temporal void 2 — occupying another organism's temporal experience / Ophrys apifera"),
    S!(278, Dragon, "Kwe'zhal",     "Temporal void 3 — lineage collapsed into undifferentiated now / Thraustochytrid"),
    S!(279, Dragon, "Kwasha-val",   "Temporal void 4 — persistence through temporal incoherence / Magicicada septendecim"),
    S!(280, Dragon, "Zhrkwe-na",    "Temporal void 5 — persistence through total replacement of visible substrate / Pando"),
    S!(281, Dragon, "Kwokvesh",     "Temporal void 6 — identity without continuity / Turritopsis dohrnii temporal"),
    S!(282, Dragon, "Vzhrkwe",      "Temporal void 7 — persistence by violating the rule of persistence / Bdelloid rotifer"),
    S!(283, Dragon, "Kwokrash-rhe", "Temporal void 8 — visible death does not equal actual organism's death / Ganoderma spp."),
    S!(284, Dragon, "Rhkwe-vun",    "Temporal void 9 — outside evolutionary time while subject to it / Vaceletia spp."),
    S!(285, Dragon, "Kwazhvu-nokte","Temporal void 10 — temporal gap with no biological explanation for closure / Syntrichia caninervis"),

    // ── Virus (Tongue 10) — bytes 286–315 ────────────────────────────────────
    S!(286, Virus, "Plave",    "Ordinal 1 — 5' terminus / ordinal origin before the first base"),
    S!(287, Virus, "Plaro",    "Ordinal 2 — 3' terminus / ordinal end"),
    S!(288, Virus, "Plahan",   "Ordinal 3 — Ha-Na / A-U standard pairing / positive principle meeting integrative directly"),
    S!(289, Virus, "Plaung",   "Ordinal 4 — Wu-Ung / G-C mediated pairing / full traversal resolved / triple bond"),
    S!(290, Virus, "Plaha",    "Ordinal 5 — Ha free / A unpaired / positive principle without complement"),
    S!(291, Virus, "Plana",    "Ordinal 6 — Na free / U unpaired / pure traversal point / neither pole claiming"),
    S!(292, Virus, "Plawu",    "Ordinal 7 — Wu free / G unpaired / mediation implicate seeking root"),
    S!(293, Virus, "Plaoku",   "Ordinal 8 — Ung free / C unpaired / mediation implicate at rest"),
    S!(294, Virus, "Plavik",   "Ordinal 9 — Codon / triplet unit / minimal ordinal unit of meaning"),
    S!(295, Virus, "Plavikro", "Ordinal 10 — Reading frame / where segmentation begins determines what the sequence means"),
    S!(296, Virus, "Jruve",    "Orthogonal 1 — Hairpin loop / simplest fold / sequence turns back on itself"),
    S!(297, Virus, "Jrushan",  "Orthogonal 2 — Stem / stable double-stranded region from intramolecular pairing"),
    S!(298, Virus, "Jrulok",   "Orthogonal 3 — Internal loop / asymmetric unpaired region within a stem"),
    S!(299, Virus, "Jruval",   "Orthogonal 4 — Bulge / single unpaired base on one side of a stem"),
    S!(300, Virus, "Jru'wun",  "Orthogonal 5 — G-U wobble / Wu-Na near-fit / mediation implicate touching root"),
    S!(301, Virus, "Jruvekna", "Orthogonal 6 — Pseudoknot / fold crossing another fold / spatial self-reference"),
    S!(302, Virus, "Jrukash",  "Orthogonal 7 — Junction / three or more stems meeting at a point"),
    S!(303, Virus, "Jruvashko","Orthogonal 8 — Kissing loops / two hairpin loops pairing / second-order fold"),
    S!(304, Virus, "Jrukashro","Orthogonal 9 — Coaxial stack / two stems stacking end-to-end"),
    S!(305, Virus, "Jrunokvre","Orthogonal 10 — Multibranch loop / four or more stems at a single junction"),
    S!(306, Virus, "Wikve",    "Catalytic 1 — Hammerhead ribozyme / self-cleavage / simplest catalytic form"),
    S!(307, Virus, "Wikro",    "Catalytic 2 — Hairpin ribozyme / reversible cleavage and ligation"),
    S!(308, Virus, "Wikhan",   "Catalytic 3 — HDV ribozyme / viral self-cleavage / catalysis at alive/not-alive boundary"),
    S!(309, Virus, "Wikval",   "Catalytic 4 — Group I intron / self-splicing / sequence removing itself"),
    S!(310, Virus, "Wikvalna", "Catalytic 5 — Group II intron / prior before the prior / ancestor of spliceosome"),
    S!(311, Virus, "Wikung",   "Catalytic 6 — Ribosomal RNA / peptide bond formation / the original translator"),
    S!(312, Virus, "Wikaro",   "Catalytic 7 — Telomerase RNA / template-directed extension / anti-terminus"),
    S!(313, Virus, "Wiknasha", "Catalytic 8 — snRNA / splicing catalysis / RNA mind inside protein body"),
    S!(314, Virus, "Wikshavel","Catalytic 9 — Aptamer / ligand-activated fold switch / conditional catalysis"),
    S!(315, Virus, "Wiknokvre","Catalytic 10 — Replicase / RNA copying RNA / the self-replicating prior"),
];

// Tongues 11 (Bacteria) through 24 (Djinn) continue at bytes 316+.
// Extend this array as tongue entries are attested.