from typing import Any, List
from .errors import AssertionFailure
from .jsonpath import extract

def assert_equals(actual: Any, expected: Any) -> None: ...
def assert_exists(values: List[Any]) -> None: ...
def assert_contains(values: List[Any], expected: Any) -> None: ...
def assert_not_contains(values: List[Any], forbidden: Any) -> None: ...
def assert_count_equals(values: List[Any], count: int) -> None: ...
def assert_count_gte(values: List[Any], count: int) -> None: ...
